### ISSUE TITLE
Laravel v9 support

### ISSUE THREAD

**Issue by roelVerdonschot** [helpscout/helpscout-api-php-laravel#13]
Is it possible to add Laravel v9 support.

**Comment by bkuhl** [comment]
Thanks for creating this issue!  I've just updated `master` to be installable with Laravel 9.  Can you give it a go and if it works well we'll ship a version for it?

**Comment by roelVerdonschot** [comment]
Composer is installing, Thanks! 
I haven't tested the helpscout api

**Comment by martinsbalodis** [comment]
@bkuhl Please create a release tag.

**Comment by bkuhl** [comment]
👋  Thanks for the nudge @martinsbalodis, it's been [tagged here](https://github.com/helpscout/helpscout-api-php-laravel/releases/tag/2.1.1)
