### ISSUE TITLE
PHP API Client v3?

### ISSUE THREAD

**Issue by JonLaliberte** [helpscout/helpscout-api-php-laravel#8]
Looks like this currently pulls v2 of the PHP client API, any plans to move this up to v3?

**Comment by bkuhl** [comment]
Thanks for pointing that out, I've opened a PR to pull in v3.

**Comment by bkuhl** [comment]
Use [v2.0.0](https://github.com/helpscout/helpscout-api-php-laravel/releases/tag/2.0.0) to pull in PHP SDK v3.

**Comment by JonLaliberte** [comment]
Great, thanks!
